LRCTL - Merge script with official version

diff --git a/sandpit/lrctl b/sandpit/lrctl
--- a/sandpit/lrctl
+++ b/sandpit/lrctl
@@ -8,7 +8,7 @@ script_name=$(basename "${BASH_SOURCE[0]}")
 # === LRCTL VARIABLES ===
 
 lrctl_debug=0
-lrctl_version="6.5.9"
+lrctl_version="6.5.12"
 lrctl_image=""
 lrctl_new_shell_after_group_membership=1
 lrctl_docker_membership_return_code=255
@@ -260,13 +260,22 @@ ensureUserIsInDockerGroup() {
 
 # check if docker is installed on machine
 installDockerCE() {
-  curl -fsSL https://get.docker.com/ | sh
-  sudo systemctl start docker
-  sudo systemctl enable docker
-  # Disable exit on error so that we can capture the return status from ensureUserIsInDockerGroup.
-  set +e
-  ensureUserIsInDockerGroup
-  set -e
+    # Check if the distribution is Oracle or Rocky
+    lsb_dis=$(get_distribution)
+    if [[ ( "$lsb_dis" == "ol" ) || ( "$lsb_dis" == "rocky" ) ]]; then
+        echo "Installing docker.."
+        dnf remove -y runc
+        dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
+        dnf install -y docker-ce --nobest
+    else
+        curl -fsSL https://get.docker.com/ | sh
+    fi
+    sudo systemctl start docker
+    sudo systemctl enable docker
+    # Disable exit on error so that we can capture the return status from ensureUserIsInDockerGroup.
+    set +e
+    ensureUserIsInDockerGroup
+    set -e
 }
 
 get_distribution() {
